
export const divisions = [
	{ id: '1', name: 'Barishal' },
	{ id: '2', name: 'Chattogram' },
	{ id: '3', name: 'Dhaka' },
	{ id: '4', name: 'Khulna' },
	{ id: '5', name: 'Rajshahi' },
	{ id: '6', name: 'Rangpur' },
	{ id: '7', name: 'Sylhet' },
	{ id: '8', name: 'Mymensingh' },
];

export const districts = [
    { id: "1", division_id: "3", name: "Dhaka" },
    { id: "2", division_id: "3", name: "Faridpur" },
    { id: "3", division_id: "3", name: "Gazipur" },
    { id: "4", division_id: "3", name: "Gopalganj" },
    { id: "5", division_id: "8", name: "Jamalpur" },
    { id: "6", division_id: "3", name: "Kishoreganj" },
    { id: "7", division_id: "3", name: "Madaripur" },
    { id: "8", division_id: "3", name: "Manikganj" },
    { id: "9", division_id: "3", name: "Munshiganj" },
    { id: "10", division_id: "8", name: "Mymensingh" },
    { id: "11", division_id: "3", name: "Narayanganj" },
    { id: "12", division_id: "3", name: "Narsingdi" },
    { id: "13", division_id: "8", name: "Netrokona" },
    { id: "14", division_id: "3", name: "Rajbari" },
    { id: "15", division_id: "3", name: "Shariatpur" },
    { id: "16", division_id: "8", name: "Sherpur" },
    { id: "17", division_id: "3", name: "Tangail" },
    { id: "18", division_id: "2", name: "Bandarban" },
    { id: "19", division_id: "2", name: "Brahmanbaria" },
    { id: "20", division_id: "2", name: "Chandpur" },
    { id: "21", division_id: "2", name: "Chattogram" },
    { id: "22", division_id: "2", name: "Cumilla" },
    { id: "23", division_id: "2", name: "Cox's Bazar" },
    { id: "24", division_id: "2", name: "Feni" },
    { id: "25", division_id: "2", name: "Khagrachhari" },
    { id: "26", division_id: "2", name: "Lakshmipur" },
    { id: "27", division_id: "2", name: "Noakhali" },
    { id: "28", division_id: "2", name: "Rangamati" },
    { id: "29", division_id: "5", name: "Bogura" },
    { id: "30", division_id: "5", name: "Joypurhat" },
    { id: "31", division_id: "5", name: "Naogaon" },
    { id: "32", division_id: "5", name: "Natore" },
    { id: "33", division_id: "5", name: "Nawabganj" },
    { id: "34", division_id: "5", name: "Pabna" },
    { id: "35", division_id: "5", name: "Rajshahi" },
    { id: "36", division_id: "5", name: "Sirajgonj" },
    { id: "37", division_id: "6", name: "Dinajpur" },
    { id: "38", division_id: "6", name: "Gaibandha" },
    { id: "39", division_id: "6", name: "Kurigram" },
    { id: "40", division_id: "6", name: "Lalmonirhat" },
    { id: "41", division_id: "6", name: "Nilphamari" },
    { id: "42", division_id: "6", name: "Panchagarh" },
    { id: "43", division_id: "6", name: "Rangpur" },
    { id: "44", division_id: "6", name: "Thakurgaon" },
    { id: "45", division_id: "1", name: "Barguna" },
    { id: "46", division_id: "1", name: "Barishal" },
    { id: "47", division_id: "1", name: "Bhola" },
    { id: "48", division_id: "1", name: "Jhalokati" },
    { id: "49", division_id: "1", name: "Patuakhali" },
    { id: "50", division_id: "1", name: "Pirojpur" },
    { id: "51", division_id: "4", name: "Bagerhat" },
    { id: "52", division_id: "4", name: "Chuadanga" },
    { id: "53", division_id: "4", name: "Jashore" },
    { id: "54", division_id: "4", name: "Jhenaidah" },
    { id: "55", division_id: "4", name: "Khulna" },
    { id: "56", division_id: "4", name: "Kushtia" },
    { id: "57", division_id: "4", name: "Magura" },
    { id: "58", division_id: "4", name: "Meherpur" },
    { id: "59", division_id: "4", name: "Narail" },
    { id: "60", division_id: "4", name: "Satkhira" },
    { id: "61", division_id: "7", name: "Habiganj" },
    { id: "62", division_id: "7", name: "Moulvibazar" },
    { id: "63", division_id: "7", name: "Sunamganj" },
    { id: "64", division_id: "7", name: "Sylhet" }
];

export const upazilas = [
    { id: "1", district_id: "1", name: "Dhamrai" },
    { id: "2", district_id: "1", name: "Dohar" },
    { id: "3", district_id: "1", name: "Keraniganj" },
    { id: "4", district_id: "1", name: "Nawabganj" },
    { id: "5", district_id: "1", name: "Savar" },
    { id: "6", district_id: "2", name: "Faridpur Sadar" },
    { id: "7", district_id: "2", name: "Alfadanga" },
    { id: "8", district_id: "2", name: "Boalmari" },
    { id: "9", district_id: "2", name: "Bhanga" },
    { id: "10", district_id: "2", name: "Nagarkanda" },
    { id: "11", district_id: "2", name: "Charbhadrasan" },
    { id: "12", district_id: "2", name: "Madhukhali" },
    { id: "13", district_id: "2", name: "Saltha" },
    { id: "14", district_id: "3", name: "Gazipur Sadar" },
    { id: "15", district_id: "3", name: "Kaliakair" },
    { id: "16", district_id: "3", name: "Kapasia" },
    { id: "17", district_id: "3", name: "Sreepur" },
    { id: "18", district_id: "3", name: "Kaliganj" },
    { id: "19", district_id: "4", name: "Gopalganj Sadar" },
    { id: "20", district_id: "4", name: "Kashiani" },
    { id: "21", district_id: "4", name: "Tungipara" },
    { id: "22", district_id: "4", name: "Kotalipara" },
    { id: "23", district_id: "4", name: "Muksudpur" },
    { id: "24", district_id: "5", name: "Jamalpur Sadar" },
    { id: "25", district_id: "5", name: "Melandah" },
    { id: "26", district_id: "5", name: "Islampur" },
    { id: "27", district_id: "5", name: "Dewanganj" },
    { id: "28", district_id: "5", name: "Sarishabari" },
    { id: "29", district_id: "5", name: "Madarganj" },
    { id: "30", district_id: "5", name: "Baksiganj" },
    { id: "31", district_id: "6", name: "Kishoreganj Sadar" },
    { id: "32", district_id: "6", name: "Hossainpur" },
    { id: "33", district_id: "6", name: "Karimganj" },
    { id: "34", district_id: "6", name: "Tarail" },
    { id: "35", district_id: "6", name: "Pakundia" },
    { id: "36", district_id: "6", name: "Katiadi" },
    { id: "37", district_id: "6", name: "Kuliarchar" },
    { id: "38", district_id: "6", name: "Bhairab" },
    { id: "39", district_id: "6", name: "Nikli" },
    { id: "40", district_id: "6", name: "Mithamain" },
    { id: "41", district_id: "6", name: "Itna" },
    { id: "42", district_id: "6", name: "Austagram" },
    { id: "43", district_id: "6", name: "Bajitpur" },
    { id: "44", district_id: "7", name: "Madaripur Sadar" },
    { id: "45", district_id: "7", name: "Shibchar" },
    { id: "46", district_id: "7", name: "Kalkini" },
    { id: "47", district_id: "7", name: "Rajoir" },
    { id: "48", district_id: "8", name: "Manikganj Sadar" },
    { id: "49", district_id: "8", name: "Singair" },
    { id: "50", district_id: "8", name: "Shivalaya" },
    { id: "51", district_id: "8", name: "Saturia" },
    { id: "52", district_id: "8", name: "Harirampur" },
    { id: "53", district_id: "8", name: "Ghior" },
    { id: "54", district_id: "8", name: "Daulatpur" },
    { id: "55", district_id: "9", name: "Munshiganj Sadar" },
    { id: "56", district_id: "9", name: "Sreenagar" },
    { id: "57", district_id: "9", name: "Sirajdikhan" },
    { id: "58", district_id: "9", name: "Louhajang" },
    { id: "59", district_id: "9", name: "Gazaria" },
    { id: "60", district_id: "9", name: "Tongibari" },
    { id: "61", district_id: "10", name: "Mymensingh Sadar" },
    { id: "62", district_id: "10", name: "Bhaluka" },
    { id: "63", district_id: "10", name: "Trishal" },
    { id: "64", district_id: "10", name: "Haluaghat" },
    { id: "65", district_id: "10", name: "Muktagachha" },
    { id: "66", district_id: "10", name: "Dhobaura" },
    { id: "67", district_id: "10", name: "Fulbaria" },
    { id: "68", district_id: "10", name: "Gaffargaon" },
    { id: "69", district_id: "10", name: "Gauripur" },
    { id: "70", district_id: "10", name: "Ishwarganj" },
    { id: "71", district_id: "10", name: "Nandail" },
    { id: "72", district_id: "10", name: "Phulpur" },
    { id: "73", district_id: "11", name: "Narayanganj Sadar" },
    { id: "74", district_id: "11", name: "Araihazar" },
    { id: "75", district_id: "11", name: "Bandar" },
    { id: "76", district_id: "11", name: "Rupganj" },
    { id: "77", district_id: "11", name: "Sonargaon" },
    { id: "78", district_id: "12", name: "Narsingdi Sadar" },
    { id: "79", district_id: "12", name: "Belabo" },
    { id: "80", district_id: "12", name: "Monohardi" },
    { id: "81", district_id: "12", name: "Palash" },
    { id: "82", district_id: "12", name: "Raipura" },
    { id: "83", district_id: "12", name: "Shibpur" },
    { id: "84", district_id: "13", name: "Netrokona Sadar" },
    { id: "85", district_id: "13", name: "Atpara" },
    { id: "86", district_id: "13", name: "Barhatta" },
    { id: "87", district_id: "13", name: "Durgapur" },
    { id: "88", district_id: "13", name: "Kalmakanda" },
    { id: "89", district_id: "13", name: "Kendua" },
    { id: "90", district_id: "13", name: "Madan" },
    { id: "91", district_id: "13", name: "Mohanganj" },
    { id: "92", district_id: "13", name: "Purbadhala" },
    { id: "93", district_id: "13", name: "Khaliajuri" },
    { id: "94", district_id: "14", name: "Rajbari Sadar" },
    { id: "95", district_id: "14", name: "Goalandaghat" },
    { id: "96", district_id: "14", name: "Pangsha" },
    { id: "97", district_id: "14", name: "Baliakandi" },
    { id: "98", district_id: "14", name: "Kalukhali" },
    { id: "99", district_id: "15", name: "Shariatpur Sadar" },
    { id: "100", district_id: "15", name: "Damudya" },
    { id: "101", district_id: "15", name: "Naria" },
    { id: "102", district_id: "15", name: "Zanjira" },
    { id: "103", district_id: "15", name: "Bhedarganj" },
    { id: "104", district_id: "15", name: "Gosairhat" },
    { id: "105", district_id: "16", name: "Sherpur Sadar" },
    { id: "106", district_id: "16", name: "Nakla" },
    { id: "107", district_id: "16", name: "Sreebardi" },
    { id: "108", district_id: "16", name: "Jhenaigati" },
    { id: "109", district_id: "16", name: "Nalitabari" },
    { id: "110", district_id: "17", name: "Tangail Sadar" },
    { id: "111", district_id: "17", name: "Gopalpur" },
    { id: "112", district_id: "17", name: "Basail" },
    { id: "113", district_id: "17", name: "Bhuapur" },
    { id: "114", district_id: "17", name: "Delduar" },
    { id: "115", district_id: "17", name: "Ghatail" },
    { id: "116", district_id: "17", name: "Kalihati" },
    { id: "117", district_id: "17", name: "Madhupur" },
    { id: "118", district_id: "17", name: "Mirzapur" },
    { id: "119", district_id: "17", name: "Nagarpur" },
    { id: "120", district_id: "17", name: "Sakhipur" },
    { id: "121", district_id: "17", name: "Dhanbari" },
    { id: "122", district_id: "18", name: "Bandarban Sadar" },
    { id: "123", district_id: "18", name: "Thanchi" },
    { id: "124", district_id: "18", name: "Lama" },
    { id: "125", district_id: "18", name: "Naikhongchhari" },
    { id: "126", district_id: "18", name: "Ali Kadam" },
    { id: "127", district_id: "18", name: "Rowangchhari" },
    { id: "128", district_id: "18", name: "Ruma" },
    { id: "129", district_id: "19", name: "Brahmanbaria Sadar" },
    { id: "130", district_id: "19", name: "Ashuganj" },
    { id: "131", district_id: "19", name: "Nasirnagar" },
    { id: "132", district_id: "19", name: "Nabinagar" },
    { id: "133", district_id: "19", name: "Sarail" },
    { id: "134", district_id: "19", name: "Kasba" },
    { id: "135", district_id: "19", name: "Akhaura" },
    { id: "136", district_id: "19", name: "Bancharampur" },
    { id: "137", district_id: "19", name: "Bijoynagar" },
    { id: "138", district_id: "20", name: "Chandpur Sadar" },
    { id: "139", district_id: "20", name: "Hajiganj" },
    { id: "140", district_id: "20", name: "Kachua" },
    { id: "141", district_id: "20", name: "Faridganj" },
    { id: "142", district_id: "20", name: "Haimchar" },
    { id: "143", district_id: "20", name: "Matlab Dakshin" },
    { id: "144", district_id: "20", name: "Matlab Uttar" },
    { id: "145", district_id: "20", name: "Shahrasti" },
    { id: "146", district_id: "21", name: "Anwara" },
    { id: "147", district_id: "21", name: "Banshkhali" },
    { id: "148", district_id: "21", name: "Boalkhali" },
    { id: "149", district_id: "21", name: "Chandanaish" },
    { id: "150", district_id: "21", name: "Fatikchhari" },
    { id: "151", district_id: "21", name: "Hathazari" },
    { id: "152", district_id: "21", name: "Lohagara" },
    { id: "153", district_id: "21", name: "Mirsharai" },
    { id: "154", district_id: "21", name: "Patiya" },
    { id: "155", district_id: "21", name: "Rangunia" },
    { id: "156", district_id: "21", name: "Raozan" },
    { id: "157", district_id: "21", name: "Sandwip" },
    { id: "158", district_id: "21", name: "Satkania" },
    { id: "159", district_id: "21", name: "Sitakunda" },
    { id: "160", district_id: "22", name: "Barura" },
    { id: "161", district_id: "22", name: "Brahmanpara" },
    { id: "162", district_id: "22", name: "Burichang" },
    { id: "163", district_id: "22", name: "Chandina" },
    { id: "164", district_id: "22", name: "Chauddagram" },
    { id: "165", district_id: "22", name: "Daudkandi" },
    { id: "166", district_id: "22", name: "Debidwar" },
    { id: "167", district_id: "22", name: "Homna" },
    { id: "168", district_id: "22", name: "Laksam" },
    { id: "169", district_id: "22", name: "Muradnagar" },
    { id: "170", district_id: "22", name: "Nangalkot" },
    { id: "171", district_id: "22", name: "Cumilla Sadar Dakshin" },
    { id: "172", district_id: "22", name: "Meghna" },
    { id: "173", district_id: "22", name: "Monohargonj" },
    { id: "174", district_id: "22", name: "Titas" },
    { id: "175", district_id: "23", name: "Cox's Bazar Sadar" },
    { id: "176", district_id: "23", name: "Chakaria" },
    { id: "177", district_id: "23", name: "Kutubdia" },
    { id: "178", district_id: "23", name: "Ukhiya" },
    { id: "179", district_id: "23", name: "Maheshkhali" },
    { id: "180", district_id: "23", name: "Pekua" },
    { id: "181", district_id: "23", name: "Ramu" },
    { id: "182", district_id: "23", name: "Teknaf" },
    { id: "183", district_id: "24", name: "Feni Sadar" },
    { id: "184", district_id: "24", name: "Chhagalnaiya" },
    { id: "185", district_id: "24", name: "Daganbhuiyan" },
    { id: "186", district_id: "24", name: "Parshuram" },
    { id: "187", district_id: "24", name: "Fulgazi" },
    { id: "188", district_id: "24", name: "Sonagazi" },
    { id: "189", district_id: "25", name: "Khagrachhari Sadar" },
    { id: "190", district_id: "25", name: "Dighinala" },
    { id: "191", district_id: "25", name: "Panchhari" },
    { id: "192", district_id: "25", name: "Laxmichhari" },
    { id: "193", district_id: "25", name: "Mohalchhari" },
    { id: "194", district_id: "25", name: "Manikchhari" },
    { id: "195", district_id: "25", name: "Ramgarh" },
    { id: "196", district_id: "25", name: "Matiranga" },
    { id: "197", district_id: "26", name: "Lakshmipur Sadar" },
    { id: "198", district_id: "26", name: "Raipur" },
    { id: "199", district_id: "26", name: "Ramganj" },
    { id: "200", district_id: "26", name: "Ramgati" },
    { id: "201", district_id: "26", name: "Kamalnagar" },
    { id: "202", district_id: "27", name: "Noakhali Sadar" },
    { id: "203", district_id: "27", name: "Begumganj" },
    { id: "204", district_id: "27", name: "Chatkhil" },
    { id: "205", district_id: "27", name: "Companyganj" },
    { id: "206", district_id: "27", name: "Shenbag" },
    { id: "207", district_id: "27", name: "Hatiya" },
    { id: "208", district_id: "27", name: "Kobirhat" },
    { id: "209", district_id: "27", name: "Sonaimori" },
    { id: "210", district_id: "27", name: "Suborno Char" },
    { id: "211", district_id: "28", name: "Rangamati Sadar" },
    { id: "212", district_id: "28", name: "Belaichhari" },
    { id: "213", district_id: "28", name: "Bagaichhari" },
    { id: "214", district_id: "28", name: "Barkal" },
    { id: "215", district_id: "28", name: "Juraichhari" },
    { id: "216", district_id: "28", name: "Rajasthali" },
    { id: "217", district_id: "28", name: "Kaptai" },
    { id: "218", district_id: "28", name: "Langadu" },
    { id: "219", district_id: "28", name: "Naniarchar" },
    { id: "220", district_id: "28", name: "Kaukhali" },
    { id: "221", district_id: "29", name: "Bogura Sadar" },
    { id: "222", district_id: "29", name: "Shibganj" },
    { id: "223", district_id: "29", name: "Sonatala" },
    { id: "224", district_id: "29", name: "Gabtali" },
    { id: "225", district_id: "29", name: "Sariakandi" },
    { id: "226", district_id: "29", name: "Adamdighi" },
    { id: "227", district_id: "29", name: "Dupchanchia" },
    { id: "228", district_id: "29", name: "Dhunat" },
    { id: "229", district_id: "29", name: "Kahaloo" },
    { id: "230", district_id: "29", name: "Nandigram" },
    { id: "231", district_id: "29", name: "Sherpur" },
    { id: "232", district_id: "29", name: "Shajahanpur" },
    { id: "233", district_id: "30", name: "Joypurhat Sadar" },
    { id: "234", district_id: "30", name: "Akkelpur" },
    { id: "235", district_id: "30", name: "Kalai" },
    { id: "236", district_id: "30", name: "Khetlal" },
    { id: "237", district_id: "30", name: "Panchbibi" },
    { id: "238", district_id: "31", name: "Naogaon Sadar" },
    { id: "239", district_id: "31", name: "Atrai" },
    { id: "240", district_id: "31", name: "Badalgachhi" },
    { id: "241", district_id: "31", name: "Manda" },
    { id: "242", district_id: "31", name: "Dhamoirhat" },
    { id: "243", district_id: "31", name: "Mohadevpur" },
    { id: "244", district_id: "31", name: "Niamatpur" },
    { id: "245", district_id: "31", name: "Patnitala" },
    { id: "246", district_id: "31", name: "Porsha" },
    { id: "247", district_id: "31", name: "Raninagar" },
    { id: "248", district_id: "31", name: "Sapahar" },
    { id: "249", district_id: "32", name: "Natore Sadar" },
    { id: "250", district_id: "32", name: "Baraigram" },
    { id: "251", district_id: "32", name: "Bagatipara" },
    { id: "252", district_id: "32", name: "Lalpur" },
    { id: "253", district_id: "32", name: "Natore Sadar" },
    { id: "254", district_id: "32", name: "Singra" },
    { id: "255", district_id: "33", name: "Nawabganj Sadar" },
    { id: "256", district_id: "33", name: "Bholahat" },
    { id: "257", district_id: "33", name: "Gomastapur" },
    { id: "258", district_id: "33", name: "Nachole" },
    { id: "259", district_id: "33", name: "Shibganj" },
    { id: "260", district_id: "34", name: "Pabna Sadar" },
    { id: "261", district_id: "34", name: "Atgharia" },
    { id: "262", district_id: "34", name: "Bera" },
    { id: "263", district_id: "34", name: "Bhangura" },
    { id: "264", district_id: "34", name: "Chatmohar" },
    { id: "265", district_id: "34", name: "Faridpur" },
    { id: "266", district_id: "34", name: "Ishwardi" },
    { id: "267", district_id: "34", name: "Santhia" },
    { id: "268", district_id: "34", name: "Sujanagar" },
    { id: "269", district_id: "35", name: "Bagha" },
    { id: "270", district_id: "35", name: "Bagmara" },
    { id: "271", district_id: "35", name: "Charghat" },
    { id: "272", district_id: "35", name: "Durgapur" },
    { id: "273", district_id: "35", name: "Godagari" },
    { id: "274", district_id: "35", name: "Mohanpur" },
    { id: "275", district_id: "35", name: "Paba" },
    { id: "276", district_id: "35", name: "Puthia" },
    { id: "277", district_id: "35", name: "Tanore" },
    { id: "278", district_id: "36", name: "Sirajganj Sadar" },
    { id: "279", district_id: "36", name: "Belkuchi" },
    { id: "280", district_id: "36", name: "Chauhali" },
    { id: "281", district_id: "36", name: "Kamarkhanda" },
    { id: "282", district_id: "36", name: "Kazipur" },
    { id: "283", district_id: "36", name: "Raiganj" },
    { id: "284", district_id: "36", name: "Shahjadpur" },
    { id: "285", district_id: "36", name: "Tarash" },
    { id: "286", district_id: "36", name: "Ullahpara" },
    { id: "287", district_id: "37", name: "Dinajpur Sadar" },
    { id: "288", district_id: "37", name: "Birampur" },
    { id: "289", district_id: "37", name: "Birganj" },
    { id: "290", district_id: "37", name: "Biral" },
    { id: "291", district_id: "37", name: "Bochaganj" },
    { id: "292", district_id: "37", name: "Chirirbandar" },
    { id: "293", district_id: "37", name: "Phulbari" },
    { id: "294", district_id: "37", name: "Ghoraghat" },
    { id: "295", district_id: "37", name: "Hakimpur" },
    { id: "296", district_id: "37", name: "Kaharole" },
    { id: "297", district_id: "37", name: "Khansama" },
    { id: "298", district_id: "37", name: "Nawabganj" },
    { id: "299", district_id: "37", name: "Parbatipur" },
    { id: "300", district_id: "38", name: "Gaibandha Sadar" },
    { id: "301", district_id: "38", name: "Fulchhari" },
    { id: "302", district_id: "38", name: "Gobindaganj" },
    { id: "303", district_id: "38", name: "Palashbari" },
    { id: "304", district_id: "38", name: "Sadullapur" },
    { id: "305", district_id: "38", name: "Saghata" },
    { id: "306", district_id: "38", name: "Sundarganj" },
    { id: "307", district_id: "39", name: "Kurigram Sadar" },
    { id: "308", district_id: "39", name: "Bhurungamari" },
    { id: "309", district_id: "39", name: "Char Rajibpur" },
    { id: "310", district_id: "39", name: "Chilmari" },
    { id: "311", district_id: "39", name: "Phulbari" },
    { id: "312", district_id: "39", name: "Nageshwari" },
    { id: "313", district_id: "39", name: "Rajarhat" },
    { id: "314", district_id: "39", name: "Raomari" },
    { id: "315", district_id: "39", name: "Ulipur" },
    { id: "316", district_id: "40", name: "Lalmonirhat Sadar" },
    { id: "317", district_id: "40", name: "Aditmari" },
    { id: "318", district_id: "40", name: "Kaliganj" },
    { id: "319", district_id: "40", name: "Hatibandha" },
    { id: "320", district_id: "40", name: "Patgram" },
    { id: "321", district_id: "41", name: "Nilphamari Sadar" },
    { id: "322", district_id: "41", name: "Dimla" },
    { id: "323", district_id: "41", name: "Domar" },
    { id: "324", district_id: "41", name: "Jaldhaka" },
    { id: "325", district_id: "41", name: "Kishoreganj" },
    { id: "326", district_id: "41", name: "Saidpur" },
    { id: "327", district_id: "42", name: "Panchagarh Sadar" },
    { id: "328", district_id: "42", name: "Atwari" },
    { id: "329", district_id: "42", name: "Boda" },
    { id: "330", district_id: "42", name: "Debiganj" },
    { id: "331", district_id: "42", name: "Tetulia" },
    { id: "332", district_id: "43", name: "Rangpur Sadar" },
    { id: "333", district_id: "43", name: "Badarganj" },
    { id: "334", district_id: "43", name: "Gangachhara" },
    { id: "335", district_id: "43", name: "Kaunia" },
    { id: "336", district_id: "43", name: "Mithapukur" },
    { id: "337", district_id: "43", name: "Pirgachha" },
    { id: "338", district_id: "43", name: "Pirganj" },
    { id: "339", district_id: "43", name: "Taraganj" },
    { id: "340", district_id: "44", name: "Thakurgaon Sadar" },
    { id: "341", district_id: "44", name: "Baliadangi" },
    { id: "342", district_id: "44", name: "Haripur" },
    { id: "343", district_id: "44", name: "Ranisankail" },
    { id: "344", district_id: "44", name: "Pirganj" },
    { id: "345", district_id: "45", name: "Barguna Sadar" },
    { id: "346", district_id: "45", name: "Amtali" },
    { id: "347", district_id: "45", name: "Taltali" },
    { id: "348", district_id: "45", name: "Patharghata" },
    { id: "349", district_id: "45", name: "Bamna" },
    { id: "350", district_id: "45", name: "Betagi" },
    { id: "351", district_id: "46", name: "Barishal Sadar" },
    { id: "352", district_id: "46", name: "Agailjhara" },
    { id: "353", district_id: "46", name: "Babuganj" },
    { id: "354", district_id: "46", name: "Bakerganj" },
    { id: "355", district_id: "46", name: "Banaripara" },
    { id: "356", district_id: "46", name: "Gaurnadi" },
    { id: "357", district_id: "46", name: "Hizla" },
    { id: "358", district_id: "46", name: "Mehendiganj" },
    { id: "359", district_id: "46", name: "Muladi" },
    { id: "360", district_id: "46", name: "Wazirpur" },
    { id: "361", district_id: "47", name: "Bhola Sadar" },
    { id: "362", district_id: "47", name: "Burhanuddin" },
    { id: "363", district_id: "47", name: "Char Fasson" },
    { id: "364", district_id: "47", name: "Daulatkhan" },
    { id: "365", district_id: "47", name: "Lalmohan" },
    { id: "366", district_id: "47", name: "Manpura" },
    { id: "367", district_id: "47", name: "Tazumuddin" },
    { id: "368", district_id: "48", name: "Jhalokati Sadar" },
    { id: "369", district_id: "48", name: "Kathalia" },
    { id: "370", district_id: "48", name: "Nalchity" },
    { id: "371", district_id: "48", name: "Rajapur" },
    { id: "372", district_id: "49", name: "Patuakhali Sadar" },
    { id: "373", district_id: "49", name: "Bauphal" },
    { id: "374", district_id: "49", name: "Dashmina" },
    { id: "375", district_id: "49", name: "Galachipa" },
    { id: "376", district_id: "49", name: "Kalapara" },
    { id: "377", district_id: "49", name: "Mirzaganj" },
    { id: "378", district_id: "49", name: "Rangabali" },
    { id: "379", district_id: "50", name: "Pirojpur Sadar" },
    { id: "380", district_id: "50", name: "Bhandaria" },
    { id: "381", district_id: "50", name: "Kawkhali" },
    { id: "382", district_id: "50", name: "Mathbaria" },
    { id: "383", district_id: "50", name: "Nazirpur" },
    { id: "384", district_id: "50", name: "Nesarabad" },
    { id: "385", district_id: "50", name: "Zianagar" },
    { id: "386", district_id: "51", name: "Bagerhat Sadar" },
    { id: "387", district_id: "51", name: "Chitalmari" },
    { id: "388", district_id: "51", name: "Fakirhat" },
    { id: "389", district_id: "51", name: "Kachua" },
    { id: "390", district_id: "51", name: "Mollahat" },
    { id: "391", district_id: "51", name: "Mongla" },
    { id: "392", district_id: "51", name: "Morrelganj" },
    { id: "393", district_id: "51", name: "Rampal" },
    { id: "394", district_id: "51", name: "Sarankhola" },
    { id: "395", district_id: "52", name: "Chuadanga Sadar" },
    { id: "396", district_id: "52", name: "Alamdanga" },
    { id: "397", district_id: "52", name: "Damurhuda" },
    { id: "398", district_id: "52", name: "Jibannagar" },
    { id: "399", district_id: "53", name: "Jashore Sadar" },
    { id: "400", district_id: "53", name: "Abhaynagar" },
    { id: "401", district_id: "53", name: "Bagherpara" },
    { id: "402", district_id: "53", name: "Chaugachha" },
    { id: "403", district_id: "53", name: "Jhikargachha" },
    { id: "404", district_id: "53", name: "Keshabpur" },
    { id: "405", district_id: "53", name: "Manirampur" },
    { id: "406", district_id: "53", name: "Sharsha" },
    { id: "407", district_id: "54", name: "Jhenaidah Sadar" },
    { id: "408", district_id: "54", name: "Harinakunda" },
    { id: "409", district_id: "54", name: "Kaliganj" },
    { id: "410", district_id: "54", name: "Kotchandpur" },
    { id: "411", district_id: "54", name: "Maheshpur" },
    { id: "412", district_id: "54", name: "Shailkupa" },
    { id: "413", district_id: "55", name: "Terokhada" },
    { id: "414", district_id: "55", name: "Batiaghata" },
    { id: "415", district_id: "55", name: "Dacope" },
    { id: "416", district_id: "55", name: "Dighalia" },
    { id: "417", district_id: "55", name: "Dumuria" },
    { id: "418", district_id: "55", name: "Koyra" },
    { id: "419", district_id: "55", name: "Paikgachha" },
    { id: "420", district_id: "55", name: "Phultala" },
    { id: "421", district_id: "55", name: "Rupsha" },
    { id: "422", district_id: "56", name: "Kushtia Sadar" },
    { id: "423", district_id: "56", name: "Bheramara" },
    { id: "424", district_id: "56", name: "Daulatpur" },
    { id: "425", district_id: "56", name: "Khoksa" },
    { id: "426", district_id: "56", name: "Kumarkhali" },
    { id: "427", district_id: "56", name: "Mirpur" },
    { id: "428", district_id: "57", name: "Magura Sadar" },
    { id: "429", district_id: "57", name: "Mohammadpur" },
    { id: "430", district_id: "57", name: "Shalikha" },
    { id: "431", district_id: "57", name: "Sreepur" },
    { id: "432", district_id: "58", name: "Meherpur Sadar" },
    { id: "433", district_id: "58", name: "Gangni" },
    { id: "434", district_id: "58", name: "Mujibnagar" },
    { id: "435", district_id: "59", name: "Narail Sadar" },
    { id: "436", district_id: "59", name: "Kalia" },
    { id: "437", district_id: "59", name: "Lohagara" },
    { id: "438", district_id: "60", name: "Satkhira Sadar" },
    { id: "439", district_id: "60", name: "Assasuni" },
    { id: "440", district_id: "60", name: "Debhata" },
    { id: "441", district_id: "60", name: "Kalaroa" },
    { id: "442", district_id: "60", name: "Kaliganj" },
    { id: "443", district_id: "60", name: "Shyamnagar" },
    { id: "444", district_id: "60", name: "Tala" },
    { id: "445", district_id: "61", name: "Habiganj Sadar" },
    { id: "446", district_id: "61", name: "Ajmiriganj" },
    { id: "447", district_id: "61", name: "Bahubal" },
    { id: "448", district_id: "61", name: "Baniachang" },
    { id: "449", district_id: "61", name: "Chunarughat" },
    { id: "450", district_id: "61", name: "Lakhai" },
    { id: "451", district_id: "61", name: "Madhabpur" },
    { id: "452", district_id: "61", name: "Nabiganj" },
    { id: "453", district_id: "62", name: "Moulvibazar Sadar" },
    { id: "454", district_id: "62", name: "Barlekha" },
    { id: "455", district_id: "62", name: "Juri" },
    { id: "456", district_id: "62", name: "Kamalganj" },
    { id: "457", district_id: "62", name: "Kulaura" },
    { id: "458", district_id: "62", name: "Rajnagar" },
    { id: "459", district_id: "62", name: "Sreemangal" },
    { id: "460", district_id: "63", name: "Sunamganj Sadar" },
    { id: "461", district_id: "63", name: "Bishwamvarpur" },
    { id: "462", district_id: "63", name: "Chhatak" },
    { id: "463", district_id: "63", name: "Derai" },
    { id: "464", district_id: "63", name: "Dharampasha" },
    { id: "465", district_id: "63", name: "Dowarabazar" },
    { id: "466", district_id: "63", name: "Jagannathpur" },
    { id: "467", district_id: "63", name: "Jamalganj" },
    { id: "468", district_id: "63", name: "Sullah" },
    { id: "469", district_id: "63", name: "Tahirpur" },
    { id: "470", district_id: "64", name: "Sylhet Sadar" },
    { id: "471", district_id: "64", name: "Balaganj" },
    { id: "472", district_id: "64", name: "Beanibazar" },
    { id: "473", district_id: "64", name: "Bishwanath" },
    { id: "474", district_id: "64", name: "Companiganj" },
    { id: "475", district_id: "64", name: "Fenchuganj" },
    { id: "476", district_id: "64", name: "Golapganj" },
    { id: "477", district_id: "64", name: "Gowainghat" },
    { id: "478", district_id: "64", name: "Jaintiapur" },
    { id: "479", district_id: "64", name: "Kanaighat" },
    { id: "480", district_id: "64", name: "Zakiganj" },
    { id: "481", district_id: "64", name: "Dakshin Surma" },
];
