
import { ProficiancyLevel } from '@/interfaces/common.interface';
import { addDays, format, subDays, subMonths, subYears } from 'date-fns';
import type { Activity, Application, Jobseeker, Job } from './types';


export const jobseekers: Jobseeker[] = [
	{
		id: 'c1',
		personalInfo: {
			firstName: 'Alice',
			lastName: 'Johnson',
			fatherName: 'George Johnson',
			motherName: 'Mary Johnson',
            user: {
			    email: 'alice.j@example.com',
			    phone: '123-456-7890',
            },
			dateOfBirth: format(subYears(new Date(), 30), 'yyyy-MM-dd'),
			gender: 'Female',
			maritalStatus: 'Married',
			nationality: 'Bangladeshi',
            religion: 'Islam',
            professionalStatus: 'Experienced',
			nid: '1234567890123',
			presentAddress: '123 Tech Avenue, Gulshan, Dhaka, 1212',
			permanentAddress: '456 Home Street, Savar, Dhaka, 1340',
			profileImage: { filePath: 'https://picsum.photos/seed/alice/100/100' } as any,
			careerObjective: 'Senior Frontend Developer with 8+ years of experience',
			linkedInProfile: 'https://linkedin.com/in/alicejohnson',
		},
		academicInfo: [
			{
				degree: 'B.S. in Computer Science',
				institution: 'Stanford University',
				graduationYear: 2016,
				certificateUrls: ['/certs/cert1.pdf', '/certs/cert2.pdf'],
			},
		],
		professionalInfo: [
			{
				company: 'TechCorp',
				role: 'Senior Frontend Developer',
				fromDate: format(new Date(2019, 0, 1), 'yyyy-MM-dd'),
				isPresent: true,
				responsibilities: ['Led development of a new design system', 'Mentored junior developers'],
			},
			{
				company: 'Innovate LLC',
				role: 'Frontend Developer',
				fromDate: format(new Date(2016, 5, 1), 'yyyy-MM-dd'),
				toDate: format(new Date(2018, 11, 31), 'yyyy-MM-dd'),
				isPresent: false,
				responsibilities: [
					'Built and maintained client-facing web applications',
					'Collaborated with UI/UX designers',
				],
			},
		],
		skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Node.js', 'Figma'],
		certifications: [
			{
				name: 'Certified Kubernetes Application Developer',
				issuingOrganization: 'The Linux Foundation',
				issueDate: '2022-01-15',
			},
		],
		languages: [
			{ languageId: 1, proficiency: 'NATIVE' },
			{ languageId: 2, proficiency: 'ADVANCED' },
		],
		publications: [
			{
				id: 'pub1',
				title: 'The Rise of Server-Side Rendering',
				publisher: 'Smashing Magazine',
				publicationDate: '2023-05-20',
				url: 'https://example.com',
			},
		],
		awards: [{ id: 1, name: 'Developer of the Year', description: 'TechCorp', date: '2021-12-20' }],
		trainings: [],
		resumes: [],
		status: 'Active',
	},
	{
		id: 'c2',
		personalInfo: {
			firstName: 'Bob',
			lastName: 'Smith',
			fatherName: 'Robert Smith',
			motherName: 'Susan Smith',
			user: {
                email: 'bob.s@example.com',
			    phone: '234-567-8901',
            },
			dateOfBirth: format(subYears(new Date(), 35), 'yyyy-MM-dd'),
			gender: 'Male',
			maritalStatus: 'Single',
			nationality: 'Bangladeshi',
            religion: 'Christianity',
            professionalStatus: 'Mid-Level',
			presentAddress: '456 Innovation Drive, Panchlaish, Chattogram, 4203',
			permanentAddress: '456 Innovation Drive, Panchlaish, Chattogram, 4203',
			profileImage: { filePath: 'https://picsum.photos/seed/bob/100/100' } as any,
			careerObjective: 'Product Manager driving innovation and growth',
		},
		academicInfo: [
			{
				degree: 'MBA',
				institution: 'Columbia Business School',
				graduationYear: 2018,
			},
		],
		professionalInfo: [
			{
				company: 'Solutions Inc.',
				role: 'Product Manager',
				fromDate: format(new Date(2018, 8, 1), 'yyyy-MM-dd'),
				isPresent: true,
				responsibilities: [
					'Defined product roadmap for B2B SaaS platform',
					'Conducted market research and user interviews',
				],
			},
		],
		skills: ['Product Management', 'Agile', 'JIRA', 'Market Research', 'Roadmap Planning'],
		certifications: [],
		languages: [{ languageId: 1, proficiency: 'NATIVE' }],
		publications: [],
		awards: [],
		trainings: [],
		resumes: [
			// { id: 'res3', fileName: 'Bob_Smith_Product_Resume.pdf', url: '/resumes/bob_smith_resume.pdf', isActive: true, createdAt: format(subDays(new Date(), 30), 'yyyy-MM-dd') }
		],
		status: 'Passive',
	},
	{
		id: 'c3',
		personalInfo: {
			firstName: 'Charlie',
			lastName: 'Brown',
			fatherName: 'Charles Brown Sr.',
			motherName: 'Sally Brown',
            user: {
			    email: 'charlie.b@example.com',
			    phone: '345-678-9012',
            },
			dateOfBirth: format(subYears(new Date(), 28), 'yyyy-MM-dd'),
			gender: 'Male',
			maritalStatus: 'Single',
			nationality: 'Bangladeshi',
            religion: 'Hinduism',
            professionalStatus: 'Entry-Level',
			presentAddress: '789 ML Lane, Sylhet Sadar, Sylhet, 3100',
			permanentAddress: '789 ML Lane, Sylhet Sadar, Sylhet, 3100',
			profileImage: { filePath: 'https://picsum.photos/seed/charlie/100/100' } as any,
			careerObjective: 'Data Scientist passionate about machine learning',
		},
		academicInfo: [
			{
				degree: 'M.S. in Data Science',
				institution: 'University of Texas at Austin',
				graduationYear: 2020,
			},
		],
		professionalInfo: [
			{
				company: 'DataWiz',
				role: 'Data Scientist',
				fromDate: format(new Date(2020, 0, 15), 'yyyy-MM-dd'),
				isPresent: true,
				responsibilities: [
					'Developed predictive models for customer churn',
					'Built data visualization dashboards in Tableau',
				],
			},
		],
		skills: ['Python', 'TensorFlow', 'PyTorch', 'SQL', 'Tableau', 'Machine Learning'],
		certifications: [],
		languages: [{ languageId: 1, proficiency: 'NATIVE' }],
		publications: [],
		awards: [],
		trainings: [],
		resumes: [
			// { id: 'res4', fileName: 'Charlie_Brown_Data_Science.pdf', url: '/resumes/charlie_brown_resume.pdf', isActive: true, createdAt: format(subDays(new Date(), 5), 'yyyy-MM-dd') }
		],
		status: 'Active',
	},
	{
		id: 'c4',
		personalInfo: {
			firstName: 'Diana',
			lastName: 'Prince',
			fatherName: 'Zeus',
			motherName: 'Hippolyta',
			user: {
                email: 'diana.p@example.com',
			    phone: '456-789-0123',
            },
			dateOfBirth: format(subYears(new Date(), 26), 'yyyy-MM-dd'),
			gender: 'Female',
			maritalStatus: 'Single',
			nationality: 'Bangladeshi',
            religion: 'Buddhism',
            professionalStatus: 'Student',
			presentAddress: '101 Design Street, Boalia, Rajshahi, 6000',
			permanentAddress: '101 Design Street, Boalia, Rajshahi, 6000',
			profileImage: { filePath: 'https://picsum.photos/seed/diana/100/100' } as any,
			careerObjective: 'UX/UI Designer creating intuitive user experiences',
		},
		academicInfo: [
			{
				degree: 'B.A. in Graphic Design',
				institution: 'Rhode Island School of Design',
				graduationYear: 2019,
			},
		],
		professionalInfo: [
			{
				company: 'Creative Minds',
				role: 'UX/UI Designer',
				fromDate: format(new Date(2019, 6, 1), 'yyyy-MM-dd'),
				isPresent: true,
				responsibilities: ['Designed user flows and wireframes', 'Conducted usability testing sessions'],
			},
		],
		skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
		certifications: [],
		languages: [{ languageId: 1, proficiency: 'NATIVE' }],
		publications: [],
		awards: [],
		trainings: [],
		resumes: [
			// { id: 'res5', fileName: 'Diana_Prince_UX_Portfolio_Resume.pdf', url: '/resumes/diana_prince_resume.pdf', isActive: true, createdAt: format(subWeeks(new Date(), 2), 'yyyy-MM-dd') }
		],
		status: 'Hired',
	},
];

export const jobs: Job[] = [
	{
		id: 'j1',
		title: 'Assistant Director',
		department: 'Bangladesh Bank',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 55,000 - 65,000',
		description:
			'Bangladesh Bank is seeking qualified candidates for the position of Assistant Director to contribute to the central banking operations.',
		responsibilities: [
			'Assisting in monetary policy formulation.',
			'Conducting economic research and analysis.',
			'Supervising financial institutions.',
			'Coordinate department inputs for the Monetary Policy Statement and quarterly review reports.',
			'Lead or co-lead on-site/off-site supervision missions and draft risk-assessment memoranda for scheduled banks/NBFIs.',
			'Monitor liquidity conditions and money-market developments; prepare daily briefs for senior management.',
			'Review and clear statistical returns, balance-of-payments tables and financial-stability indicators before release.',
			'Represent Bangladesh Bank in inter-ministerial or IFI working groups on payment systems, digital finance, climate-risk, etc.',
			'Oversee the implementation of new BB circulars within supervised entities; track compliance milestones.',
			'Coach junior analysts and interns; conduct internal training modules on Basel norms, stress-testing and data governance.',
		],
		requirements: [
			'Masters degree in Economics, Finance, or related field.',
			'Strong analytical and communication skills.',
			'Knowledge of banking regulations.',
			'Minimum 2 years’ experience in a central bank, commercial bank treasury, or reputable economic-research outfit.',
			'Demonstrated exposure to econometric packages (Stata, R, EViews) and large data sets; SQL/Python familiarity preferred.',
			'Working knowledge of Basel III capital/liquidity standards, CAMELS rating framework and Bangladesh’s Banking Companies Act.',
			'Ability to write concise technical notes in English; Bangla drafting skill for policy circulars is an advantage.',
			'Strong presentation acumen—must be comfortable defending analytical findings to Deputy Governors or Board committees.',
			'Professional integrity, gender sensitivity and a clean disciplinary record; existing BB employees must attach latest ACRs.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 5), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 25), 'yyyy-MM-dd'),
	},
	{
		id: 'j2',
		title: 'Medical Officer',
		department: 'Ministry of Health and Family Welfare',
		location: 'Multiple Locations',
		type: 'Full-time',
		salaryRange: 'BDT 40,000 - 50,000',
		description:
			'The Ministry of Health is looking for dedicated Medical Officers to provide healthcare services in government hospitals and health complexes.',
		responsibilities: [
			'Providing medical treatment to patients.',
			'Managing public health programs.',
			'Maintaining medical records.',
			'Coordinate department inputs for the Monetary Policy Statement and quarterly review reports.',
			'Lead or co-lead on-site/off-site supervision missions and draft risk-assessment memoranda for scheduled banks/NBFIs.',
			'Monitor liquidity conditions and money-market developments; prepare daily briefs for senior management.',
			'Review and clear statistical returns, balance-of-payments tables and financial-stability indicators before release.',
			'Represent Bangladesh Bank in inter-ministerial or IFI working groups on payment systems, digital finance, climate-risk, etc.',
			'Oversee the implementation of new BB circulars within supervised entities; track compliance milestones.',
			'Coach junior analysts and interns; conduct internal training modules on Basel norms, stress-testing and data governance.',
		],
		requirements: [
			'MBBS degree from a recognized university.',
			'Valid registration with BMDC.',
			'Experience in clinical practice.',
			'Minimum 2 years’ experience in a central bank, commercial bank treasury, or reputable economic-research outfit.',
			'Demonstrated exposure to econometric packages (Stata, R, EViews) and large data sets; SQL/Python familiarity preferred.',
			'Working knowledge of Basel III capital/liquidity standards, CAMELS rating framework and Bangladesh’s Banking Companies Act.',
			'Ability to write concise technical notes in English; Bangla drafting skill for policy circulars is an advantage.',
			'Strong presentation acumen—must be comfortable defending analytical findings to Deputy Governors or Board committees.',
			'Professional integrity, gender sensitivity and a clean disciplinary record; existing BB employees must attach latest ACRs.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 12), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 18), 'yyyy-MM-dd'),
	},
	{
		id: 'j3',
		title: 'Project Engineer (Civil)',
		department: 'Roads and Highways Department',
		location: 'Dhaka',
		type: 'Contract',
		salaryRange: 'BDT 70,000 - 85,000',
		description:
			'Seeking a skilled Civil Engineer for infrastructure development projects, including bridges and highways.',
		responsibilities: [
			'Supervising construction projects.',
			'Ensuring quality control and safety standards.',
			'Preparing project reports and documentation.',
			'Coordinate department inputs for the Monetary Policy Statement and quarterly review reports.',
			'Lead or co-lead on-site/off-site supervision missions and draft risk-assessment memoranda for scheduled banks/NBFIs.',
			'Monitor liquidity conditions and money-market developments; prepare daily briefs for senior management.',
			'Review and clear statistical returns, balance-of-payments tables and financial-stability indicators before release.',
			'Represent Bangladesh Bank in inter-ministerial or IFI working groups on payment systems, digital finance, climate-risk, etc.',
			'Oversee the implementation of new BB circulars within supervised entities; track compliance milestones.',
			'Coach junior analysts and interns; conduct internal training modules on Basel norms, stress-testing and data governance.',
		],
		requirements: [
			'B.Sc. in Civil Engineering.',
			'Minimum 5 years of experience in road or bridge construction.',
			'Proficiency in AutoCAD and project management software.',
			'Minimum 2 years’ experience in a central bank, commercial bank treasury, or reputable economic-research outfit.',
			'Demonstrated exposure to econometric packages (Stata, R, EViews) and large data sets; SQL/Python familiarity preferred.',
			'Working knowledge of Basel III capital/liquidity standards, CAMELS rating framework and Bangladesh’s Banking Companies Act.',
			'Ability to write concise technical notes in English; Bangla drafting skill for policy circulars is an advantage.',
			'Strong presentation acumen—must be comfortable defending analytical findings to Deputy Governors or Board committees.',
			'Professional integrity, gender sensitivity and a clean disciplinary record; existing BB employees must attach latest ACRs.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 20), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 10), 'yyyy-MM-dd'),
	},
	{
		id: 'j4',
		title: 'Upazila Nirbahi Officer (UNO)',
		department: 'Ministry of Public Administration',
		location: 'Various Upazilas',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description:
			'A prestigious role in the Bangladesh Civil Service responsible for administration and development at the Upazila level.',
		responsibilities: [
			'Implementing government policies.',
			'Coordinating with various government departments.',
			'Overseeing local development projects.',
			'Coordinate department inputs for the Monetary Policy Statement and quarterly review reports.',
			'Lead or co-lead on-site/off-site supervision missions and draft risk-assessment memoranda for scheduled banks/NBFIs.',
			'Monitor liquidity conditions and money-market developments; prepare daily briefs for senior management.',
			'Review and clear statistical returns, balance-of-payments tables and financial-stability indicators before release.',
			'Represent Bangladesh Bank in inter-ministerial or IFI working groups on payment systems, digital finance, climate-risk, etc.',
			'Oversee the implementation of new BB circulars within supervised entities; track compliance milestones.',
			'Coach junior analysts and interns; conduct internal training modules on Basel norms, stress-testing and data governance.',
		],
		requirements: [
			'Qualified in Bangladesh Civil Service (BCS) examination.',
			'Strong leadership and administrative skills.',
			'Commitment to public service.',
			'Minimum 2 years’ experience in a central bank, commercial bank treasury, or reputable economic-research outfit.',
			'Demonstrated exposure to econometric packages (Stata, R, EViews) and large data sets; SQL/Python familiarity preferred.',
			'Working knowledge of Basel III capital/liquidity standards, CAMELS rating framework and Bangladesh’s Banking Companies Act.',
			'Ability to write concise technical notes in English; Bangla drafting skill for policy circulars is an advantage.',
			'Strong presentation acumen—must be comfortable defending analytical findings to Deputy Governors or Board committees.',
			'Professional integrity, gender sensitivity and a clean disciplinary record; existing BB employees must attach latest ACRs.',
		],
		status: 'Closed',
		postedDate: format(subMonths(new Date(), 2), 'yyyy-MM-dd'),
		applicationDeadline: format(subMonths(new Date(), 1), 'yyyy-MM-dd'),
	},
	{
		id: 'j5',
		title: 'IT Officer',
		department: 'ICT Division',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 45,000 - 55,000',
		description:
			'The ICT Division requires a skilled IT Officer to manage and maintain government IT infrastructure and support digital initiatives.',
		responsibilities: [
			'Network administration and security.',
			'System maintenance and troubleshooting.',
			'Supporting e-Governance projects.',
		],
		requirements: [
			'B.Sc. in Computer Science or IT.',
			'Experience with network hardware, servers, and cybersecurity best practices.',
			'Relevant certifications (e.g., CCNA, MCSA) are a plus.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 8), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 22), 'yyyy-MM-dd'),
	},
	{
		id: 'j6',
		title: 'Customs Officer',
		department: 'National Board of Revenue (NBR)',
		location: 'Chittagong',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description:
			'An important role in revenue collection and trade facilitation at the ports and borders of Bangladesh.',
		responsibilities: [
			'Assessing and collecting customs duties and taxes.',
			'Preventing smuggling and illegal trade.',
			'Inspecting cargo and documentation.',
		],
		requirements: [
			'Qualified through the BCS (Customs and Excise) cadre examination.',
			'Strong integrity and attention to detail.',
			'Knowledge of customs laws and tariffs.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 25), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 5), 'yyyy-MM-dd'),
	},
	{
		id: 'j7',
		title: 'Power Plant Manager',
		department: 'Bangladesh Power Development Board (BPDB)',
		location: 'Gazipur',
		type: 'Full-time',
		salaryRange: 'BDT 90,000 - 110,000',
		description:
			'Experienced manager sought to oversee the operations and maintenance of a government-owned power plant.',
		responsibilities: [
			'Managing daily power plant operations.',
			'Ensuring compliance with safety and environmental regulations.',
			'Leading a team of engineers and technicians.',
		],
		requirements: [
			'B.Sc. in Electrical or Mechanical Engineering.',
			'10+ years of experience in power plant management.',
			'Strong technical and leadership skills.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 3), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 27), 'yyyy-MM-dd'),
	},
	{
		id: 'j8',
		title: 'Lecturer (Computer Science)',
		department: 'Ministry of Education',
		location: 'Various Govt. Colleges',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description:
			'Seeking passionate educators to teach Computer Science at the higher secondary and undergraduate levels in government colleges.',
		responsibilities: [
			'Delivering lectures and conducting lab sessions.',
			'Developing course materials and assessing students.',
			'Participating in academic committees.',
		],
		requirements: [
			'Masters in Computer Science from a reputable university.',
			'Strong academic record.',
			'Prior teaching experience is preferred.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 15), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 15), 'yyyy-MM-dd'),
	},
	{
		id: 'j9',
		title: 'Urban Planner',
		department: 'Rajdhani Unnayan Kartripakkha (RAJUK)',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 60,000 - 75,000',
		description:
			'Join RAJUK to contribute to the planned development of Dhaka city, focusing on sustainable urban growth and infrastructure.',
		responsibilities: [
			'Developing master plans and detailed area plans.',
			'Reviewing development proposals.',
			'Conducting urban research and data analysis.',
		],
		requirements: [
			'Bachelors or Masters in Urban and Regional Planning (URP).',
			'Knowledge of GIS software and planning regulations.',
			'Experience in a government planning agency is a plus.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 22), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 8), 'yyyy-MM-dd'),
	},
	{
		id: 'j10',
		title: 'Scientific Officer',
		department: 'Bangladesh Council of Scientific and Industrial Research (BCSIR)',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'As per BCSIR Pay Scale',
		description:
			'A research-oriented position for individuals passionate about scientific innovation and industrial development.',
		responsibilities: [
			'Conducting research in a specified scientific field.',
			'Publishing research findings.',
			'Collaborating with industries for technology transfer.',
		],
		requirements: [
			'M.Sc. or PhD in a relevant scientific discipline (e.g., Chemistry, Physics, Biology).',
			'Proven research capabilities and publications.',
			'Strong laboratory skills.',
		],
		status: 'Archived',
		postedDate: format(subMonths(new Date(), 3), 'yyyy-MM-dd'),
		applicationDeadline: format(subMonths(new Date(), 2), 'yyyy-MM-dd'),
	},
	{
		id: 'j11',
		title: 'Port Operations Officer',
		department: 'Chittagong Port Authority',
		location: 'Chittagong',
		type: 'Full-time',
		salaryRange: 'BDT 50,000 - 60,000',
		description: "Assist in the management of day-to-day operations at the nation's primary seaport.",
		responsibilities: [
			'Coordinating vessel traffic and berthing.',
			'Managing cargo handling and storage.',
			'Ensuring port safety and security protocols are followed.',
		],
		requirements: [
			'Masters in Maritime Science, Management, or a related field.',
			'Experience in port or shipping industry.',
			'Excellent organizational and communication skills.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 7), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 23), 'yyyy-MM-dd'),
	},
	{
		id: 'j12',
		title: 'Agronomist',
		department: 'Bangladesh Agricultural Research Institute (BARI)',
		location: 'Gazipur',
		type: 'Full-time',
		salaryRange: 'As per BARI Pay Scale',
		description:
			'Conduct research to improve crop yield, quality, and resistance to diseases for ensuring national food security.',
		responsibilities: [
			'Designing and conducting field experiments.',
			'Developing improved crop varieties.',
			'Disseminating research findings to farmers.',
		],
		requirements: [
			'M.Sc. or PhD in Agronomy or a related agricultural science.',
			'Strong background in agricultural research.',
			'Fieldwork experience is essential.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 30), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 0), 'yyyy-MM-dd'),
	},
	{
		id: 'j13',
		title: 'Assistant Commissioner (Land)',
		department: 'Ministry of Land',
		location: 'Various Districts',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description: 'A key administrative role in land management and revenue collection at the upazila level.',
		responsibilities: [
			'Managing land records and mutation.',
			'Resolving land disputes.',
			'Administering government-owned (khas) land.',
		],
		requirements: [
			'Qualified through the BCS (Admin) cadre examination.',
			'Strong understanding of land laws in Bangladesh.',
			'Excellent conflict resolution skills.',
		],
		status: 'Closed',
		postedDate: format(subMonths(new Date(), 4), 'yyyy-MM-dd'),
		applicationDeadline: format(subMonths(new Date(), 3), 'yyyy-MM-dd'),
	},
	{
		id: 'j14',
		title: 'Telecommunication Engineer',
		department: 'Bangladesh Telecommunication Company Ltd (BTCL)',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 65,000 - 80,000',
		description: 'Work on the expansion and maintenance of the national telecommunication network.',
		responsibilities: [
			'Planning and implementing telecom network upgrades.',
			'Monitoring network performance.',
			'Troubleshooting and resolving technical issues.',
		],
		requirements: [
			'B.Sc. in Electrical & Electronic Engineering (EEE) or Telecommunications Engineering.',
			'Experience with fiber optics, microwave, and switching systems.',
			'Knowledge of modern telecom protocols.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 18), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 12), 'yyyy-MM-dd'),
	},
	{
		id: 'j15',
		title: 'Fisheries Officer',
		department: 'Department of Fisheries',
		location: 'Coastal Districts',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description: 'Promote sustainable aquaculture and manage fisheries resources in your assigned area.',
		responsibilities: [
			'Providing technical assistance to fish farmers.',
			'Implementing government fisheries projects.',
			'Conserving fish biodiversity.',
		],
		requirements: [
			'B.Sc. or M.Sc. in Fisheries or a related field.',
			'Practical knowledge of aquaculture techniques.',
			'Strong communication skills to work with local communities.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 40), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), -10), 'yyyy-MM-dd'),
	},
	{
		id: 'j16',
		title: 'Public Relations Officer',
		department: 'Press Information Department (PID)',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 40,000 - 50,000',
		description:
			'Manage media relations and public communications for various government ministries and departments.',
		responsibilities: [
			'Writing and distributing press releases.',
			'Organizing press conferences.',
			'Monitoring media coverage.',
		],
		requirements: [
			'Masters in Mass Communication & Journalism or Public Relations.',
			'Excellent writing skills in both Bengali and English.',
			'Experience working with media outlets.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 1), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 29), 'yyyy-MM-dd'),
	},
	{
		id: 'j17',
		title: 'Textile Engineer',
		department: 'Department of Textiles',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'BDT 50,000 - 65,000',
		description: 'Contribute to the policy-making and development of the vital textile sector of Bangladesh.',
		responsibilities: [
			'Inspecting textile mills for quality and compliance.',
			'Providing technical guidance to industry stakeholders.',
			'Working on skill development projects.',
		],
		requirements: [
			'B.Sc. in Textile Engineering.',
			'Knowledge of textile manufacturing processes and quality standards.',
			'Good analytical and interpersonal skills.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 9), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 21), 'yyyy-MM-dd'),
	},
	{
		id: 'j18',
		title: 'Assistant Secretary',
		department: 'Ministry of Foreign Affairs',
		location: 'Dhaka',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description: 'Represent Bangladesh on the global stage as a diplomat in the Bangladesh Foreign Service.',
		responsibilities: [
			'Assisting in diplomatic relations and negotiations.',
			'Providing consular services.',
			'Analyzing international affairs.',
		],
		requirements: [
			'Qualified through the BCS (Foreign Affairs) cadre examination.',
			'Excellent command of English and strong interpersonal skills.',
			'Deep knowledge of international relations and history.',
		],
		status: 'Closed',
		postedDate: format(subMonths(new Date(), 6), 'yyyy-MM-dd'),
		applicationDeadline: format(subMonths(new Date(), 5), 'yyyy-MM-dd'),
	},
	{
		id: 'j19',
		title: 'Archaeologist',
		department: 'Department of Archaeology',
		location: 'Bogura',
		type: 'Full-time',
		salaryRange: 'As per DoA Pay Scale',
		description:
			"Work on the excavation, preservation, and research of Bangladesh's rich archaeological heritage.",
		responsibilities: [
			'Leading or participating in archaeological excavations.',
			'Conserving historical sites and artifacts.',
			'Conducting research and publishing findings.',
		],
		requirements: [
			'Masters or PhD in Archaeology or Anthropology.',
			'Field experience in excavation and conservation.',
			'Passion for history and cultural heritage.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 50), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), -20), 'yyyy-MM-dd'),
	},
	{
		id: 'j20',
		title: 'Sub-Registrar',
		department: 'Directorate of Registration',
		location: 'Various Districts',
		type: 'Full-time',
		salaryRange: 'As per National Pay Scale',
		description:
			'Responsible for the registration of property deeds and other legal documents at the sub-registry office.',
		responsibilities: [
			'Registering land sale/purchase deeds.',
			'Maintaining official records of registration.',
			'Ensuring legal compliance of documents.',
		],
		requirements: [
			'LL.B or LL.M degree.',
			'Qualified through the Bangladesh Judicial Service Commission (BJSC) examination or equivalent.',
			'Meticulous and detail-oriented.',
		],
		status: 'Open',
		postedDate: format(subDays(new Date(), 28), 'yyyy-MM-dd'),
		applicationDeadline: format(addDays(new Date(), 2), 'yyyy-MM-dd'),
	},
];

export const applications: Application[] = [
	{
		id: 'app1',
		jobId: 'j1',
		jobseekerId: 'c1',
		status: 'Interview',
		applicationDate: format(subDays(new Date(), 1), 'yyyy-MM-dd'),
	},
	{
		id: 'app2',
		jobId: 'j2',
		jobseekerId: 'c2',
		status: 'Applied',
		applicationDate: format(subDays(new Date(), 8), 'yyyy-MM-dd'),
	},
	{
		id: 'app3',
		jobId: 'j3',
		jobseekerId: 'c3',
		status: 'Hired',
		applicationDate: format(subDays(new Date(), 25), 'yyyy-MM-dd'),
	},
	{
		id: 'app4',
		jobId: 'j1',
		jobseekerId: 'c3',
		status: 'Screening',
		applicationDate: format(subDays(new Date(), 1), 'yyyy-MM-dd'),
	},
	{
		id: 'app5',
		jobId: 'j5',
		jobseekerId: 'c1',
		status: 'Offered',
		applicationDate: format(subDays(new Date(), 3), 'yyyy-MM-dd'),
	},
	{
		id: 'app6',
		jobId: 'j6',
		jobseekerId: 'c2',
		status: 'Rejected',
		applicationDate: format(subDays(new Date(), 14), 'yyyy-MM-dd'),
	},
	{
		id: 'app7',
		jobId: 'j1',
		jobseekerId: 'c2',
		status: 'Shortlisted',
		applicationDate: format(subDays(new Date(), 2), 'yyyy-MM-dd'),
	},
	{
		id: 'app8',
		jobId: 'j1',
		jobseekerId: 'c4',
		status: 'Applied',
		applicationDate: format(subDays(new Date(), 3), 'yyyy-MM-dd'),
	},
];

export const activities: Activity[] = [
	{
		id: 'act1',
		user: { name: 'Admin User', avatar: 'https://picsum.photos/seed/admin/100/100' },
		action: 'posted a new job:',
		target: 'Public Relations Officer',
		timestamp: format(subDays(new Date(), 1), 'yyyy-MM-dd HH:mm'),
	},
	{
		id: 'act2',
		user: { name: 'Alice Johnson', avatar: 'https://picsum.photos/seed/alice/100/100' },
		action: 'applied for:',
		target: 'Assistant Director',
		timestamp: format(subDays(new Date(), 1), 'yyyy-MM-dd HH:mm'),
	},
	{
		id: 'act3',
		user: { name: 'Admin User', avatar: 'https://picsum.photos/seed/admin/100/100' },
		action: 'shortlisted',
		target: 'Charlie Brown for IT Officer',
		timestamp: format(new Date(), 'yyyy-MM-dd HH:mm'),
	},
	{
		id: 'act4',
		user: { name: 'Admin User', avatar: 'https://picsum.photos/seed/admin/100/100' },
		action: 'changed status of',
		target: 'Upazila Nirbahi Officer (UNO) to Closed',
		timestamp: format(subDays(new Date(), 2), 'yyyy-MM-dd HH:mm'),
	},
];
