export const AUTH_INFO = 'auth_info';
export const ACCESS_TOKEN = 'access_token';
export const REFRESH_TOKEN = 'refresh_token';

export enum ROLES {
	SUPER_ADMIN = 'SUPER_ADMIN',
	IIFC_ADMIN = 'IIFC_ADMIN',
	IIFC_OPERATOR = 'IIFC_OPERATOR',
	EXAMINER_ADMIN = 'EXAMINER_ADMIN',
	EXAMINER_OPERATOR = 'EXAMINER_OPERATOR',
	CLIENT_ADMIN = 'CLIENT_ADMIN',
	CLIENT_OPERATOR = 'CLIENT_OPERATOR',
	JOB_SEEKER = 'JOB_SEEKER',
}
